# Generated by Django 5.1.6 on 2025-05-01 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('es_desgaste', models.BooleanField(default=False)),
                ('es_contaminante', models.BooleanField(default=False)),
                ('es_aditivo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_calibracion', models.DateField(blank=True, null=True)),
                ('proxima_calibracion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lubricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('grado_viscosidad', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_desempeno', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metodo_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('equipo_requerido', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimiteCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('grado', models.CharField(max_length=20)),
                ('espuma1', models.CharField(blank=True, max_length=20, null=True)),
                ('espuma2', models.CharField(blank=True, max_length=20, null=True)),
                ('espuma3', models.CharField(blank=True, max_length=20, null=True)),
                ('chispa', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('tipo', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='LimiteViscosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('grado', models.CharField(max_length=20)),
                ('vmin', models.FloatField(blank=True, null=True)),
                ('vmax', models.FloatField(blank=True, null=True)),
                ('iv1', models.IntegerField(blank=True, null=True)),
                ('iv2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('tipo', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='ComentarioElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_verde', models.TextField(blank=True, null=True)),
                ('comentario_amarillo', models.TextField(blank=True, null=True)),
                ('comentario_rojo', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.categorialimite')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.elementoanalisis')),
            ],
            options={
                'unique_together': {('elemento', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='LimiteElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_verde', models.FloatField(blank=True, null=True)),
                ('limite_amarillo', models.FloatField(blank=True, null=True)),
                ('limite_rojo', models.FloatField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.categorialimite')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.elementoanalisis')),
            ],
            options={
                'unique_together': {('elemento', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='ReferenciaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misc.tipoequipo')),
            ],
            options={
                'unique_together': {('tipo', 'codigo')},
            },
        ),
    ]
