# Generated by Django 5.1.6 on 2026-05-27 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ColorGrasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ComentarioPredefinido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("NO_DESEADO", "No deseado")],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Comentario predefinido",
                "verbose_name_plural": "Comentarios predefinidos",
            },
        ),
        migrations.CreateModel(
            name="Condicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("magnitud", models.CharField(default="temperatura", max_length=80)),
                ("valor", models.DecimalField(decimal_places=4, max_digits=12)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["magnitud", "nombre", "valor"],
            },
        ),
        migrations.CreateModel(
            name="ElementoAnalisis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(max_length=5, unique=True)),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("valor", models.FloatField(blank=True, null=True)),
                (
                    "symbol_operation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("<", "Menor que"),
                            ("<=", "Menor o igual"),
                            ("=", "Igual"),
                            (">=", "Mayor o igual"),
                            (">", "Mayor que"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="EquipoPrueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ExtraField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tabla_relacionada", models.CharField(max_length=100)),
                ("objeto_id", models.CharField(max_length=50)),
                ("nombre_campo", models.CharField(max_length=100)),
                (
                    "tipo_campo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("numero", "Número"),
                            ("decimal", "Decimal"),
                            ("fecha", "Fecha"),
                            ("fecha_hora", "Fecha y Hora"),
                            ("booleano", "Booleano"),
                            ("opciones", "Opciones"),
                            ("archivo", "Archivo"),
                            ("email", "Email"),
                            ("url", "URL"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                ("etiqueta", models.CharField(blank=True, max_length=200, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("valor_texto", models.TextField(blank=True, null=True)),
                ("valor_numero", models.FloatField(blank=True, null=True)),
                ("valor_fecha", models.DateTimeField(blank=True, null=True)),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                ("opciones", models.JSONField(blank=True, null=True)),
                ("requerido", models.BooleanField(default=False)),
                ("orden", models.IntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("archivado", "Archivado"),
                            ("pendiente_revision", "Pendiente de Revisión"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_ultima_edicion", models.DateTimeField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("es_editable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Campo Extra",
                "verbose_name_plural": "Campos Extras",
                "db_table": "extra_fields",
                "ordering": ["tabla_relacionada", "objeto_id", "orden", "nombre_campo"],
            },
        ),
        migrations.CreateModel(
            name="Jabon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("acidez_alcali", models.CharField(max_length=50)),
                ("metodo", models.CharField(max_length=50)),
                ("valor", models.CharField(max_length=50)),
                ("agua", models.CharField(blank=True, max_length=50, null=True)),
                ("goteo", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LimiteCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c1", models.CharField(blank=True, max_length=10, null=True)),
                ("c2", models.CharField(blank=True, max_length=10, null=True)),
                ("seq_espuma", models.CharField(blank=True, max_length=20, null=True)),
                ("chispa", models.IntegerField(blank=True, null=True)),
                ("valor", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LimiteGenericoPrueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("valor", models.FloatField(blank=True, null=True)),
                (
                    "symbol_operation",
                    models.CharField(
                        choices=[
                            ("<", "Menor que"),
                            ("<=", "Menor o igual"),
                            ("=", "Igual"),
                            (">=", "Mayor o igual"),
                            (">", "Mayor que"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LimiteViscosidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v1", models.CharField(blank=True, max_length=20, null=True)),
                ("v2", models.CharField(blank=True, max_length=20, null=True)),
                ("vmin", models.FloatField(blank=True, null=True)),
                ("vmax", models.FloatField(blank=True, null=True)),
                ("iv1", models.IntegerField(blank=True, null=True)),
                ("iv2", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lubricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia", models.CharField(max_length=50, unique=True)),
                (
                    "nombre_comercial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "grado_viscosidad",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nivel_desempeno",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fabricante", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("carpeta", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarcaGrasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MetodoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=120)),
                (
                    "norma_referencia",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["equipo_prueba__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="NLGI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grado", models.CharField(max_length=10)),
                ("minimo", models.IntegerField()),
                ("maximo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Prueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "metodo_referencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unidad_medida",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_subPrueba", models.BooleanField(default=False)),
                ("parent_node", models.IntegerField(default=-1)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("viscosidad", "Viscosidad"),
                            ("calidad", "Calidad"),
                            ("elementos", "Elementos"),
                            ("otro", "Otro"),
                        ],
                        default="viscosidad",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PruebaLimite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ReferenciaEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SistemaFiltracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_iso", models.CharField(max_length=50)),
                ("tipo_sistema", models.TextField()),
                ("componentes_tipicos", models.TextField()),
                ("sensibilidad", models.CharField(max_length=50)),
                ("um_4", models.IntegerField()),
                ("um_6", models.IntegerField()),
                ("um_14", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TiposCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_c_1", models.BooleanField(default=False)),
                ("is_c_2", models.BooleanField(default=False)),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TiposViscosidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_v_1", models.BooleanField(default=False)),
                ("is_v_2", models.BooleanField(default=False)),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("simbolo", models.CharField(max_length=25, unique=True)),
                ("magnitud", models.CharField(blank=True, max_length=80, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["magnitud", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioElemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario_verde", models.TextField(blank=True, null=True)),
                ("comentario_amarillo", models.TextField(blank=True, null=True)),
                ("comentario_rojo", models.TextField(blank=True, null=True)),
                (
                    "elemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misc.elementoanalisis",
                    ),
                ),
            ],
        ),
    ]
