# Generated by Django 5.1.6 on 2025-05-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='equipo_requerido',
        ),
    ]
