# Generated by Django 5.1.6 on 2026-04-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("misc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extrafield",
            name="usuario_actualizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extrafields_actualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extrafield",
            name="usuario_creacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extrafields_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extrafield",
            name="usuario_ultima_edicion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extrafields_editados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marcagrasa",
            name="color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="misc.color"
            ),
        ),
        migrations.AddField(
            model_name="pruebalimite",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="pruebalimite",
            name="prueba",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="limite_asignado",
                to="misc.prueba",
            ),
        ),
        migrations.AddField(
            model_name="referenciaequipo",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="misc.tipoequipo"
            ),
        ),
        migrations.AddIndex(
            model_name="extrafield",
            index=models.Index(
                fields=["tabla_relacionada", "objeto_id"],
                name="extra_field_tabla_r_0d0359_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="extrafield",
            index=models.Index(fields=["estado"], name="extra_field_estado_5a0ad0_idx"),
        ),
        migrations.AddIndex(
            model_name="extrafield",
            index=models.Index(
                fields=["fecha_creacion"], name="extra_field_fecha_c_b6029a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="extrafield",
            unique_together={("tabla_relacionada", "objeto_id", "nombre_campo")},
        ),
        migrations.AlterUniqueTogether(
            name="referenciaequipo",
            unique_together={("tipo", "codigo")},
        ),
    ]
