# Generated by Django 5.1.6 on 2025-05-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_remove_prueba_equipo_requerido'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='limitecalidad',
            unique_together={('tipo',)},
        ),
        migrations.AlterUniqueTogether(
            name='limiteviscosidad',
            unique_together={('tipo',)},
        ),
        migrations.RemoveField(
            model_name='limitecalidad',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='limiteviscosidad',
            name='grado',
        ),
    ]
