# Generated by Django 5.1.6 on 2026-05-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0003_pruebas_catalogo_nuevo"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="prueba",
            new_name="misc_prueba_activo_72e516_idx",
            old_name="misc_prueba_activo_idx",
        ),
        migrations.RenameIndex(
            model_name="prueba",
            new_name="misc_prueba_acronim_88bca9_idx",
            old_name="misc_prueba_acronimo_idx",
        ),
        migrations.RenameIndex(
            model_name="prueba",
            new_name="misc_prueba_nombre__a17492_idx",
            old_name="misc_prueba_nomvar_idx",
        ),
    ]
