# Generated by Django 5.1.6 on 2025-05-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_limitecalidad_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiteviscosidad',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
