# Generated by Django 5.1.6 on 2026-05-29 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "misc",
            "0004_rename_misc_prueba_activo_idx_misc_prueba_activo_72e516_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prueba",
            name="equipo",
        ),
        migrations.RemoveField(
            model_name="prueba",
            name="tiene_submetodos",
        ),
        migrations.RemoveField(
            model_name="pruebadisposicion",
            name="prueba",
        ),
        migrations.RemoveField(
            model_name="pruebaresultado",
            name="prueba",
        ),
        migrations.RemoveField(
            model_name="pruebaseparador",
            name="prueba",
        ),
        migrations.AddField(
            model_name="pruebaresultado",
            name="tipo_dato",
            field=models.CharField(
                choices=[
                    ("numerico", "Numérico"),
                    ("texto", "Texto"),
                    ("booleano", "Sí/No"),
                ],
                default="numerico",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultado",
            name="unidad_medida",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name="MetodoPrueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("equipo", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "referencia_normativa",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre", "codigo"],
                "indexes": [
                    models.Index(
                        fields=["activo"], name="misc_metodo_activo_e79180_idx"
                    ),
                    models.Index(
                        fields=["codigo"], name="misc_metodo_codigo_2f1ac6_idx"
                    ),
                    models.Index(
                        fields=["nombre"], name="misc_metodo_nombre_1a3b75_idx"
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="prueba",
            name="metodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pruebas",
                to="misc.metodoprueba",
            ),
        ),
        migrations.CreateModel(
            name="PruebaResultadoGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etiqueta", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "prueba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos_resultado",
                        to="misc.prueba",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.AddField(
            model_name="pruebadisposicion",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disposiciones",
                to="misc.pruebaresultadogrupo",
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultado",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="misc.pruebaresultadogrupo",
            ),
        ),
        migrations.AddField(
            model_name="pruebaseparador",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="separadores",
                to="misc.pruebaresultadogrupo",
            ),
        ),
        migrations.CreateModel(
            name="SubmetodoPrueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50, null=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "metodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submetodos",
                        to="misc.metodoprueba",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.AddField(
            model_name="pruebaresultadogrupo",
            name="submetodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos_resultado",
                to="misc.submetodoprueba",
            ),
        ),
        migrations.DeleteModel(
            name="PruebaSubmetodo",
        ),
        migrations.AddIndex(
            model_name="submetodoprueba",
            index=models.Index(fields=["activo"], name="misc_submet_activo_7ffd91_idx"),
        ),
        migrations.AddIndex(
            model_name="submetodoprueba",
            index=models.Index(fields=["orden"], name="misc_submet_orden_d2a6fb_idx"),
        ),
        migrations.AddIndex(
            model_name="pruebaresultadogrupo",
            index=models.Index(fields=["activo"], name="misc_prueba_activo_24d372_idx"),
        ),
        migrations.AddIndex(
            model_name="pruebaresultadogrupo",
            index=models.Index(fields=["orden"], name="misc_prueba_orden_c450c1_idx"),
        ),
    ]
