# Generated by Django 5.1.6 on 2026-05-29 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0005_remove_prueba_equipo_remove_prueba_tiene_submetodos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PruebaResultadoComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("acronimo", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "unidad_medida",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("numerico", "Numérico"),
                            ("texto", "Texto"),
                            ("booleano", "Sí/No"),
                        ],
                        default="numerico",
                        max_length=20,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="PruebaResultadoDisposicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="Disposición principal", max_length=150),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="PruebaResultadoDisposicionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("componente", "Componente"),
                            ("separador", "Separador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="PruebaResultadoDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=150, null=True)),
                ("es_principal", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="PruebaResultadoSeparador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(max_length=10)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="PruebaSubmetodoTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="pruebadisposicion",
            name="grupo",
        ),
        migrations.RemoveField(
            model_name="pruebadisposicionitem",
            name="disposicion",
        ),
        migrations.RemoveField(
            model_name="pruebadisposicionitem",
            name="resultado",
        ),
        migrations.RemoveField(
            model_name="pruebadisposicionitem",
            name="separador",
        ),
        migrations.RemoveField(
            model_name="pruebaresultadogrupo",
            name="prueba",
        ),
        migrations.RemoveField(
            model_name="pruebaresultadogrupo",
            name="submetodo",
        ),
        migrations.RemoveField(
            model_name="pruebaseparador",
            name="grupo",
        ),
        migrations.RemoveField(
            model_name="pruebaresultado",
            name="grupo",
        ),
        migrations.RemoveField(
            model_name="pruebaresultado",
            name="tipo_dato",
        ),
        migrations.RemoveField(
            model_name="pruebaresultado",
            name="unidad_medida",
        ),
        migrations.AddField(
            model_name="pruebaresultado",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebaresultado",
            name="prueba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="misc.prueba",
            ),
        ),
        migrations.AddIndex(
            model_name="pruebaresultado",
            index=models.Index(fields=["activo"], name="misc_prueba_activo_9ad539_idx"),
        ),
        migrations.AddIndex(
            model_name="pruebaresultado",
            index=models.Index(fields=["orden"], name="misc_prueba_orden_7009a6_idx"),
        ),
        migrations.AddField(
            model_name="pruebaresultadodisposicionitem",
            name="componente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_disposicion",
                to="misc.pruebaresultadocomponente",
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultadodisposicionitem",
            name="disposicion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="misc.pruebaresultadodisposicion",
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultadodivision",
            name="resultado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisiones",
                to="misc.pruebaresultado",
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultadodisposicion",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disposiciones",
                to="misc.pruebaresultadodivision",
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultadocomponente",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="componentes",
                to="misc.pruebaresultadodivision",
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultadoseparador",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="separadores",
                to="misc.pruebaresultadodivision",
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultadodisposicionitem",
            name="separador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_disposicion",
                to="misc.pruebaresultadoseparador",
            ),
        ),
        migrations.AddField(
            model_name="pruebasubmetodotecnico",
            name="prueba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submetodos_tecnicos_configurados",
                to="misc.prueba",
            ),
        ),
        migrations.AddField(
            model_name="pruebasubmetodotecnico",
            name="submetodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pruebas_configuradas",
                to="misc.submetodoprueba",
            ),
        ),
        migrations.AddField(
            model_name="prueba",
            name="submetodos_tecnicos",
            field=models.ManyToManyField(
                blank=True,
                related_name="pruebas",
                through="misc.PruebaSubmetodoTecnico",
                to="misc.submetodoprueba",
            ),
        ),
        migrations.DeleteModel(
            name="PruebaDisposicion",
        ),
        migrations.DeleteModel(
            name="PruebaDisposicionItem",
        ),
        migrations.DeleteModel(
            name="PruebaSeparador",
        ),
        migrations.DeleteModel(
            name="PruebaResultadoGrupo",
        ),
        migrations.AddIndex(
            model_name="pruebaresultadodivision",
            index=models.Index(fields=["activo"], name="misc_prueba_activo_c1b7aa_idx"),
        ),
        migrations.AddIndex(
            model_name="pruebaresultadodivision",
            index=models.Index(fields=["orden"], name="misc_prueba_orden_a00792_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="pruebasubmetodotecnico",
            unique_together={("prueba", "submetodo")},
        ),
    ]
