# Generated by Django 5.1.6 on 2025-05-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_calidad_color_colorgrasa_jabon_marca_nlgi_marcagrasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioPredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('NORMAL', 'Normal'), ('NO_DESEADO', 'No deseado')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comentario predefinido',
                'verbose_name_plural': 'Comentarios predefinidos',
            },
        ),
    ]
