# Generated by Django 5.1.6 on 2025-05-02 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('misc', '0006_comentariopredefinido'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='categoria',
            field=models.CharField(choices=[('viscosidad', 'Viscosidad'), ('calidad', 'Calidad'), ('elementos', 'Elementos'), ('otro', 'Otro')], default='viscosidad', max_length=20),
        ),
        migrations.CreateModel(
            name='RelacionPruebaLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('tipo_lubricante', models.CharField(max_length=100)),
                ('severidad', models.CharField(choices=[('critico', 'Crítico'), ('advertencia', 'Advertencia'), ('normal', 'Normal')], max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.prueba')),
            ],
            options={
                'unique_together': {('prueba', 'content_type', 'object_id', 'tipo_equipo', 'tipo_lubricante')},
            },
        ),
    ]
