# Generated by Django 5.1.6 on 2026-05-29 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0006_pruebaresultadocomponente_pruebaresultadodisposicion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prueba",
            name="metodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pruebas",
                to="misc.metodoequipo",
            ),
        ),
    ]
