# Generated by Django 5.1.6 on 2026-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0007_alter_prueba_metodo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoGestionMuestra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("dias_habiles", models.PositiveIntegerField(default=0)),
                ("dias_calendario", models.PositiveIntegerField(default=0)),
                ("aplica_a_todos", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresas_permitidas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tipos_gestion_muestras",
                        to="misc.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de gestión de muestra",
                "verbose_name_plural": "Tipos de gestión de muestras",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["activo"], name="misc_tipoge_activo_7588a8_idx"
                    ),
                    models.Index(
                        fields=["aplica_a_todos"], name="misc_tipoge_aplica__862c7c_idx"
                    ),
                ],
            },
        ),
    ]
