# Generated by Django 5.1.6 on 2025-05-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_prueba_categoria_relacionpruebalimite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipoLaboratorio',
        ),
    ]
