# Generated by Django 5.1.6 on 2026-05-29 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0008_tipogestionmuestra"),
    ]

    operations = [
        migrations.AddField(
            model_name="lubricante",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lubricante",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lubricante",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
