# Generated by Django 5.1.6 on 2025-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_delete_equipolaboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaFiltracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=50)),
                ('tipo_sistema', models.TextField()),
                ('componentes_tipicos', models.TextField()),
                ('sensibilidad', models.CharField(max_length=50)),
                ('um_4', models.IntegerField()),
                ('um_6', models.IntegerField()),
                ('um_14', models.IntegerField()),
            ],
        ),
    ]
