# Generated by Django 5.1.6 on 2025-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_sistemafiltracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionpruebalimite',
            name='symbol_operation',
            field=models.CharField(default='equal', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relacionpruebalimite',
            name='type_operation',
            field=models.CharField(default='equal', max_length=200, null=True),
        ),
    ]
