# Generated by Django 5.1.6 on 2026-05-30 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0010_aditivograsa_espesantegrasa_fabricantelubricante_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.SlugField(max_length=120, unique=True)),
                (
                    "tipo_muestra",
                    models.CharField(
                        choices=[
                            ("aceite", "Aceite"),
                            ("grasa", "Grasa"),
                            ("ambos", "Ambos"),
                        ],
                        default="ambos",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("es_requerido_en_muestra", models.BooleanField(default=False)),
                ("permite_desconocido", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="misc_catalo_codigo_1269dc_idx"
                    ),
                    models.Index(
                        fields=["tipo_muestra", "activo"],
                        name="misc_catalo_tipo_mu_2097cc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CatalogoTecnicoCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.SlugField(max_length=120)),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("numero", "Numero"),
                            ("decimal", "Decimal"),
                            ("booleano", "Booleano"),
                            ("fecha", "Fecha"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                ("requerido", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos",
                        to="misc.catalogotecnico",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CatalogoTecnicoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.SlugField(blank=True, max_length=150, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="misc.catalogotecnico",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CatalogoTecnicoItemValor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="misc.catalogotecnicocampo",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="misc.catalogotecnicoitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PruebaFuenteLimite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_limite",
                    models.CharField(
                        choices=[
                            ("catalogo", "Catalogo tecnico"),
                            ("global", "Global"),
                            ("sin_limite", "Sin limite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operador",
                    models.CharField(
                        choices=[
                            ("rango", "Rango"),
                            ("menor_igual", "<="),
                            ("mayor_igual", ">="),
                            ("menor", "<"),
                            ("mayor", ">"),
                            ("igual", "="),
                            ("texto", "Texto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_minimo_global",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "valor_maximo_global",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "valor_texto_global",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unidad", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "comentario_normal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comentario_fuera_limite",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prioridad", models.PositiveIntegerField(default=100)),
                (
                    "campo_maximo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuentes_limite_maximo",
                        to="misc.catalogotecnicocampo",
                    ),
                ),
                (
                    "campo_minimo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuentes_limite_minimo",
                        to="misc.catalogotecnicocampo",
                    ),
                ),
                (
                    "catalogo_fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuentes_limite",
                        to="misc.catalogotecnico",
                    ),
                ),
                (
                    "componente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuentes_limite_dinamicas",
                        to="misc.pruebaresultadocomponente",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuentes_limite_dinamicas",
                        to="misc.pruebaresultadodivision",
                    ),
                ),
                (
                    "prueba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuentes_limite_dinamicas",
                        to="misc.prueba",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuentes_limite_dinamicas",
                        to="misc.pruebaresultado",
                    ),
                ),
            ],
            options={
                "ordering": ["prioridad", "prueba_id"],
            },
        ),
        migrations.AddIndex(
            model_name="catalogotecnicocampo",
            index=models.Index(
                fields=["catalogo", "activo"], name="misc_catalo_catalog_983c23_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogotecnicocampo",
            constraint=models.UniqueConstraint(
                fields=("catalogo", "codigo"), name="unique_dynamic_catalog_field_code"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogotecnicoitem",
            index=models.Index(
                fields=["catalogo", "activo"], name="misc_catalo_catalog_c51b53_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogotecnicoitem",
            constraint=models.UniqueConstraint(
                fields=("catalogo", "nombre"), name="unique_dynamic_catalog_item_name"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogotecnicoitemvalor",
            index=models.Index(
                fields=["item", "campo"], name="misc_catalo_item_id_6d454f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogotecnicoitemvalor",
            constraint=models.UniqueConstraint(
                fields=("item", "campo"), name="unique_dynamic_catalog_item_value"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebafuentelimite",
            index=models.Index(
                fields=["prueba", "activo"], name="misc_prueba_prueba__736ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebafuentelimite",
            index=models.Index(
                fields=["tipo_limite"], name="misc_prueba_tipo_li_3f1bb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebafuentelimite",
            index=models.Index(
                fields=["catalogo_fuente"], name="misc_prueba_catalog_40bafb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebafuentelimite",
            index=models.Index(
                fields=["resultado", "division", "componente"],
                name="misc_prueba_resulta_36d9ce_idx",
            ),
        ),
    ]
