# Generated by Django 5.1.6 on 2025-09-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0010_relacionpruebalimite_symbol_operation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
    ]
