# Generated by Django 5.1.6 on 2026-05-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0011_catalogotecnico_catalogotecnicocampo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pruebafuentelimite",
            name="operador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rango", "Rango"),
                    ("menor_igual", "<="),
                    ("mayor_igual", ">="),
                    ("menor", "<"),
                    ("mayor", ">"),
                    ("igual", "="),
                    ("texto", "Texto"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
