# Generated by Django 5.1.6 on 2025-09-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0011_empresa_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
