# Generated by Django 5.1.6 on 2025-09-29 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0012_alter_empresa_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tabla_relacionada", models.CharField(max_length=100)),
                ("objeto_id", models.CharField(max_length=50)),
                ("nombre_campo", models.CharField(max_length=100)),
                (
                    "tipo_campo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("numero", "Número"),
                            ("decimal", "Decimal"),
                            ("fecha", "Fecha"),
                            ("fecha_hora", "Fecha y Hora"),
                            ("booleano", "Booleano"),
                            ("opciones", "Opciones"),
                            ("archivo", "Archivo"),
                            ("email", "Email"),
                            ("url", "URL"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                ("etiqueta", models.CharField(blank=True, max_length=200, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("valor_texto", models.TextField(blank=True, null=True)),
                ("valor_numero", models.FloatField(blank=True, null=True)),
                ("valor_fecha", models.DateTimeField(blank=True, null=True)),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                ("opciones", models.JSONField(blank=True, null=True)),
                ("requerido", models.BooleanField(default=False)),
                ("orden", models.IntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("archivado", "Archivado"),
                            ("pendiente_revision", "Pendiente de Revisión"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_ultima_edicion", models.DateTimeField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("es_editable", models.BooleanField(default=True)),
                (
                    "usuario_actualizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extrafields_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extrafields_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_ultima_edicion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extrafields_editados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo Extra",
                "verbose_name_plural": "Campos Extras",
                "db_table": "extra_fields",
                "ordering": ["tabla_relacionada", "objeto_id", "orden", "nombre_campo"],
                "indexes": [
                    models.Index(
                        fields=["tabla_relacionada", "objeto_id"],
                        name="extra_field_tabla_r_0d0359_idx",
                    ),
                    models.Index(
                        fields=["estado"], name="extra_field_estado_5a0ad0_idx"
                    ),
                    models.Index(
                        fields=["fecha_creacion"], name="extra_field_fecha_c_b6029a_idx"
                    ),
                ],
                "unique_together": {("tabla_relacionada", "objeto_id", "nombre_campo")},
            },
        ),
    ]
