# Generated by Django 5.1.6 on 2026-05-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0012_alter_pruebafuentelimite_operador"),
        ("muestras", "0011_remove_muestra_muestras_mu_fabrica_394b9c_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AditivoGrasa",
        ),
        migrations.DeleteModel(
            name="EspesanteGrasa",
        ),
        migrations.DeleteModel(
            name="FabricanteLubricante",
        ),
        migrations.DeleteModel(
            name="GradoViscosidad",
        ),
        migrations.DeleteModel(
            name="NivelDesempeno",
        ),
        migrations.DeleteModel(
            name="NLGI",
        ),
        migrations.DeleteModel(
            name="UsoLubricante",
        ),
    ]
