# Generated by Django 5.1.6 on 2026-05-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0013_delete_aditivograsa_delete_espesantegrasa_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LimiteCalidad",
        ),
        migrations.DeleteModel(
            name="LimiteGenericoPrueba",
        ),
        migrations.DeleteModel(
            name="LimiteViscosidad",
        ),
        migrations.DeleteModel(
            name="Lubricante",
        ),
        migrations.RemoveField(
            model_name="pruebalimite",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="pruebalimite",
            name="prueba",
        ),
        migrations.DeleteModel(
            name="TiposCalidad",
        ),
        migrations.DeleteModel(
            name="TiposViscosidad",
        ),
        migrations.DeleteModel(
            name="PruebaLimite",
        ),
    ]
