# Generated by Django 5.1.6 on 2025-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0013_extrafield"),
    ]

    operations = [
        migrations.AddField(
            model_name="prueba",
            name="is_subPrueba",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prueba",
            name="parent_node",
            field=models.IntegerField(default=-1),
        ),
    ]
