# Generated by Django 5.1.6 on 2026-05-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0014_delete_limitecalidad_delete_limitegenericoprueba_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Calidad",
        ),
        migrations.RemoveField(
            model_name="marcagrasa",
            name="color",
        ),
        migrations.DeleteModel(
            name="ColorGrasa",
        ),
        migrations.DeleteModel(
            name="ComentarioPredefinido",
        ),
        migrations.DeleteModel(
            name="Jabon",
        ),
        migrations.DeleteModel(
            name="Marca",
        ),
        migrations.AlterUniqueTogether(
            name="referenciaequipo",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="referenciaequipo",
            name="tipo",
        ),
        migrations.DeleteModel(
            name="SistemaFiltracion",
        ),
        migrations.DeleteModel(
            name="Color",
        ),
        migrations.DeleteModel(
            name="MarcaGrasa",
        ),
        migrations.DeleteModel(
            name="ReferenciaEquipo",
        ),
        migrations.DeleteModel(
            name="TipoEquipo",
        ),
    ]
