# Generated by Django 5.1.6 on 2025-10-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0014_prueba_is_subprueba_prueba_parent_node"),
    ]

    operations = [
        migrations.RenameField(
            model_name="limitecalidad",
            old_name="espuma1",
            new_name="seq_espuma",
        ),
        migrations.RenameField(
            model_name="limitecalidad",
            old_name="espuma2",
            new_name="valor",
        ),
        migrations.RemoveField(
            model_name="limitecalidad",
            name="espuma3",
        ),
        migrations.CreateModel(
            name="LimiteGenericoPrueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("valor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "symbol_operation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type_operation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prueba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misc.prueba",
                    ),
                ),
            ],
        ),
    ]
