# Generated by Django 5.1.6 on 2025-10-09 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0015_rename_espuma1_limitecalidad_seq_espuma_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RelacionPruebaLimite",
        ),
    ]
