# Generated by Django 5.1.6 on 2026-05-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0015_delete_calidad_remove_marcagrasa_color_and_more"),
        ("reporte", "0003_remove_interpretacion_muestra_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComentarioElemento",
        ),
        migrations.DeleteModel(
            name="ElementoAnalisis",
        ),
    ]
