# Generated by Django 5.1.6 on 2025-10-09 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0016_delete_relacionpruebalimite"),
    ]

    operations = [
        migrations.AddField(
            model_name="elementoanalisis",
            name="prueba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="misc.prueba",
            ),
        ),
        migrations.AddField(
            model_name="limitecalidad",
            name="prueba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="misc.prueba",
            ),
        ),
        migrations.AddField(
            model_name="limiteelemento",
            name="prueba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="misc.prueba",
            ),
        ),
        migrations.AddField(
            model_name="limiteviscosidad",
            name="prueba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="misc.prueba",
            ),
        ),
    ]
