# Generated by Django 5.1.6 on 2026-06-01 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0016_delete_comentarioelemento_delete_elementoanalisis"),
    ]

    operations = [
        migrations.CreateModel(
            name="PruebaLimiteCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=160)),
                ("codigo", models.SlugField(max_length=140)),
                (
                    "operador",
                    models.CharField(
                        choices=[
                            ("max", "<= máximo"),
                            ("min", ">= mínimo"),
                            ("eq", "= exacto"),
                            ("warn_max", "Alerta si supera"),
                            ("warn_min", "Alerta si baja"),
                        ],
                        default="max",
                        max_length=20,
                    ),
                ),
                ("unidad", models.CharField(blank=True, max_length=30, null=True)),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["fuente_limite", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="PruebaLimiteValorItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.CharField(blank=True, max_length=120, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["item__nombre", "campo_limite__orden"],
            },
        ),
        migrations.AlterModelOptions(
            name="catalogotecnicocampo",
            options={"ordering": ["catalogo__orden", "orden", "nombre"]},
        ),
        migrations.AlterModelOptions(
            name="catalogotecnicoitem",
            options={"ordering": ["catalogo__orden", "nombre"]},
        ),
        migrations.AlterModelOptions(
            name="catalogotecnicoitemvalor",
            options={"ordering": ["item__nombre", "campo__orden"]},
        ),
        migrations.AlterModelOptions(
            name="pruebafuentelimite",
            options={"ordering": ["prioridad", "prueba__nombre_variable"]},
        ),
        migrations.RemoveConstraint(
            model_name="catalogotecnicocampo",
            name="unique_dynamic_catalog_field_code",
        ),
        migrations.RemoveConstraint(
            model_name="catalogotecnicoitem",
            name="unique_dynamic_catalog_item_name",
        ),
        migrations.RemoveConstraint(
            model_name="catalogotecnicoitemvalor",
            name="unique_dynamic_catalog_item_value",
        ),
        migrations.RemoveIndex(
            model_name="catalogotecnico",
            name="misc_catalo_codigo_1269dc_idx",
        ),
        migrations.RemoveIndex(
            model_name="catalogotecnico",
            name="misc_catalo_tipo_mu_2097cc_idx",
        ),
        migrations.RemoveIndex(
            model_name="catalogotecnicocampo",
            name="misc_catalo_catalog_983c23_idx",
        ),
        migrations.RemoveIndex(
            model_name="catalogotecnicoitem",
            name="misc_catalo_catalog_c51b53_idx",
        ),
        migrations.RemoveIndex(
            model_name="catalogotecnicoitemvalor",
            name="misc_catalo_item_id_6d454f_idx",
        ),
        migrations.RemoveIndex(
            model_name="pruebafuentelimite",
            name="misc_prueba_prueba__736ca1_idx",
        ),
        migrations.RemoveIndex(
            model_name="pruebafuentelimite",
            name="misc_prueba_tipo_li_3f1bb4_idx",
        ),
        migrations.RemoveIndex(
            model_name="pruebafuentelimite",
            name="misc_prueba_catalog_40bafb_idx",
        ),
        migrations.RemoveIndex(
            model_name="pruebafuentelimite",
            name="misc_prueba_resulta_36d9ce_idx",
        ),
        migrations.AlterUniqueTogether(
            name="catalogotecnicocampo",
            unique_together={("catalogo", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="pruebafuentelimite",
            unique_together={("prueba", "catalogo_fuente")},
        ),
        migrations.AddField(
            model_name="catalogotecnicocampo",
            name="es_campo_limite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalogotecnicocampo",
            name="es_visible_en_muestra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalogotecnicocampo",
            name="unidad",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="catalogotecnicoitem",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebafuentelimite",
            name="minimo_campos_cumplidos",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebafuentelimite",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebafuentelimite",
            name="politica_evaluacion",
            field=models.CharField(
                choices=[
                    ("todas_deben_cumplir", "Todas deben cumplir"),
                    ("alguna_debe_cumplir", "Al menos una debe cumplir"),
                    ("cantidad_minima", "Cantidad mínima de campos"),
                    ("solo_informativo", "Solo informativo"),
                ],
                default="todas_deben_cumplir",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="catalogotecnico",
            name="codigo",
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="catalogotecnico",
            name="nombre",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="catalogotecnicocampo",
            name="codigo",
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name="catalogotecnicocampo",
            name="nombre",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="catalogotecnicocampo",
            name="tipo_dato",
            field=models.CharField(
                choices=[
                    ("texto", "Texto"),
                    ("numero", "Número"),
                    ("decimal", "Decimal"),
                    ("booleano", "Booleano"),
                ],
                default="texto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="catalogotecnicoitem",
            name="codigo",
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name="catalogotecnicoitem",
            name="nombre",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="pruebafuentelimite",
            name="catalogo_fuente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fuentes_limite",
                to="misc.catalogotecnico",
            ),
        ),
        migrations.AlterField(
            model_name="pruebafuentelimite",
            name="prueba",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuentes_limite",
                to="misc.prueba",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="catalogotecnicoitem",
            unique_together={("catalogo", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="catalogotecnicoitemvalor",
            unique_together={("item", "campo")},
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="componente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campos_limite",
                to="misc.pruebaresultadocomponente",
            ),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campos_limite",
                to="misc.pruebaresultadodivision",
            ),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="fuente_limite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campos_limite",
                to="misc.pruebafuentelimite",
            ),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="resultado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campos_limite",
                to="misc.pruebaresultado",
            ),
        ),
        migrations.AddField(
            model_name="pruebalimitevaloritem",
            name="campo_limite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valores_item",
                to="misc.pruebalimitecampo",
            ),
        ),
        migrations.AddField(
            model_name="pruebalimitevaloritem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valores_limite_por_prueba",
                to="misc.catalogotecnicoitem",
            ),
        ),
        migrations.RemoveField(
            model_name="catalogotecnicocampo",
            name="requerido",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="campo_maximo",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="campo_minimo",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="comentario_fuera_limite",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="comentario_normal",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="componente",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="division",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="operador",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="resultado",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="tipo_limite",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="unidad",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="valor_maximo_global",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="valor_minimo_global",
        ),
        migrations.RemoveField(
            model_name="pruebafuentelimite",
            name="valor_texto_global",
        ),
        migrations.AlterUniqueTogether(
            name="pruebalimitecampo",
            unique_together={("fuente_limite", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="pruebalimitevaloritem",
            unique_together={("campo_limite", "item")},
        ),
    ]
