# Generated by Django 5.1.6 on 2025-10-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0017_elementoanalisis_prueba_limitecalidad_prueba_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="limitegenericoprueba",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="limitegenericoprueba",
            name="symbol_operation",
            field=models.CharField(
                choices=[
                    ("<", "Menor que"),
                    ("<=", "Menor o igual"),
                    ("=", "Igual"),
                    (">=", "Mayor o igual"),
                    (">", "Mayor que"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="limitegenericoprueba",
            name="type_operation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="limitegenericoprueba",
            name="valor",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
