# Generated by Django 5.1.6 on 2026-06-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0017_pruebalimitecampo_pruebalimitevaloritem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="nit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
