# Generated by Django 5.1.6 on 2025-10-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0018_alter_limitegenericoprueba_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="limitegenericoprueba",
            name="nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
