# Generated by Django 5.1.6 on 2025-10-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0019_alter_limitegenericoprueba_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elementoanalisis",
            name="prueba",
        ),
        migrations.RemoveField(
            model_name="limitecalidad",
            name="prueba",
        ),
        migrations.RemoveField(
            model_name="limiteelemento",
            name="prueba",
        ),
        migrations.RemoveField(
            model_name="limitegenericoprueba",
            name="prueba",
        ),
        migrations.RemoveField(
            model_name="limiteviscosidad",
            name="prueba",
        ),
    ]
