# Generated by Django 5.1.6 on 2025-10-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("misc", "0020_remove_elementoanalisis_prueba_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PruebaLimite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "prueba",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limite_asignado",
                        to="misc.prueba",
                    ),
                ),
            ],
        ),
    ]
