# Generated by Django 5.1.6 on 2026-06-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0020_lotepruebaspredefinido"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lotepruebaspredefinido",
            new_name="misc_lotepr_tipo_lo_97b1d4_idx",
            old_name="misc_lotepr_tipo_lo_5fc275_idx",
        ),
        migrations.RenameIndex(
            model_name="lotepruebaspredefinido",
            new_name="misc_lotepr_tipo_ge_52946b_idx",
            old_name="misc_lotepr_tipo_ge_720e6d_idx",
        ),
        migrations.RenameIndex(
            model_name="lotepruebaspredefinido",
            new_name="misc_lotepr_activo_8e1359_idx",
            old_name="misc_lotepr_activo_47e17d_idx",
        ),
    ]
