# Generated by Django 5.1.6 on 2025-10-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0021_pruebalimite"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comentarioelemento",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="limitecalidad",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="limiteelemento",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="limiteviscosidad",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="comentarioelemento",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="limiteelemento",
            name="categoria",
        ),
        migrations.DeleteModel(
            name="CategoriaLimite",
        ),
    ]
