# Generated by Django 5.1.6 on 2026-06-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "misc",
            "0021_rename_misc_lotepr_tipo_lo_5fc275_idx_misc_lotepr_tipo_lo_97b1d4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lotepruebaspredefinidodetalle",
            name="criterio_limite_catalogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lotes_predefinidos_detalle_criterio",
                to="misc.catalogotecnico",
            ),
        ),
        migrations.AddField(
            model_name="lotepruebaspredefinidodetalle",
            name="criterio_limite_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lotes_predefinidos_detalle_criterio",
                to="misc.catalogotecnicoitem",
            ),
        ),
    ]
