# Generated by Django 5.1.6 on 2025-10-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0022_alter_comentarioelemento_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="limiteviscosidad",
            name="tipo",
        ),
        migrations.AddField(
            model_name="limiteviscosidad",
            name="v1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="limiteviscosidad",
            name="v2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
