# Generated by Django 5.1.6 on 2026-06-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "misc",
            "0022_lotepruebaspredefinidodetalle_criterio_limite_catalogo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="block_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="read_only_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="retention_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Activa"),
                    ("READ_ONLY", "Solo lectura"),
                    ("BLOCKED", "Bloqueada"),
                    ("INACTIVE", "Inactiva"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
