# Generated by Django 5.1.6 on 2026-06-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0023_empresa_block_reason_empresa_blocked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalaComparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=140)),
                ("codigo", models.SlugField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="comentario_fuera_limite",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="comentario_no_evaluable",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="comentario_normal",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="modo_ordinal",
            field=models.CharField(
                choices=[("orden", "Orden"), ("numero_base", "Numero base")],
                default="orden",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="opciones_permitidas",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="tipo_comparacion",
            field=models.CharField(
                choices=[
                    ("numerica", "Numerica"),
                    ("texto", "Texto exacto"),
                    ("booleano", "Booleano"),
                    ("opcion", "Opcion"),
                    ("escala_ordinal", "Escala ordinal"),
                    ("informativo", "Informativo"),
                ],
                default="numerica",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultadocomponente",
            name="opciones_resultado",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebaresultadocomponente",
            name="permite_observacion",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pruebaresultadocomponente",
            name="requiere_valor",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pruebalimitecampo",
            name="operador",
            field=models.CharField(
                choices=[
                    ("max", "<= máximo"),
                    ("min", ">= mínimo"),
                    ("eq", "= exacto"),
                    ("warn_max", "Alerta si supera"),
                    ("warn_min", "Alerta si baja"),
                    ("neq", "Diferente"),
                    ("in", "En lista"),
                    ("not_in", "No en lista"),
                    ("scale_max", "Escala <= valor"),
                    ("scale_min", "Escala >= valor"),
                    ("informativo", "Informativo"),
                ],
                default="max",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pruebaresultadocomponente",
            name="tipo_dato",
            field=models.CharField(
                choices=[
                    ("numerico", "Numérico"),
                    ("texto", "Texto"),
                    ("booleano", "Sí/No"),
                    ("opcion", "Opcion"),
                    ("escala_ordinal", "Escala ordinal"),
                ],
                default="numerico",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="escala_comparacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campos_limite",
                to="misc.escalacomparacion",
            ),
        ),
        migrations.AddField(
            model_name="pruebaresultadocomponente",
            name="escala_comparacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="componentes_resultado",
                to="misc.escalacomparacion",
            ),
        ),
        migrations.CreateModel(
            name="EscalaComparacionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("etiqueta", models.CharField(max_length=80)),
                ("valor_normalizado", models.SlugField(max_length=100)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "numero_base",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("modificador", models.CharField(blank=True, max_length=20, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="misc.escalacomparacion",
                    ),
                ),
            ],
            options={
                "ordering": ["escala__nombre", "orden", "id"],
                "unique_together": {("escala", "valor_normalizado")},
            },
        ),
    ]
