# Generated by Django 5.1.6 on 2025-10-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0023_remove_limiteviscosidad_tipo_limiteviscosidad_v1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiposViscosidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_v_1", models.BooleanField(default=False)),
                ("is_v_2", models.BooleanField(default=False)),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
