# Generated by Django 5.1.6 on 2026-06-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0024_escalacomparacion_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pruebafuentelimite",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pruebafuentelimite",
            name="tipo_limite",
            field=models.CharField(
                choices=[
                    ("catalogo", "Catalogo tecnico"),
                    ("global", "Global"),
                    ("sin_limite", "Sin limite"),
                ],
                default="catalogo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pruebalimitecampo",
            name="valor_global",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="pruebafuentelimite",
            name="catalogo_fuente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fuentes_limite",
                to="misc.catalogotecnico",
            ),
        ),
    ]
