# Generated by Django 5.1.6 on 2025-10-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0024_tiposviscosidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiposCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_C_1", models.BooleanField(default=False)),
                ("is_C_2", models.BooleanField(default=False)),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="limitecalidad",
            name="tipo",
        ),
        migrations.AddField(
            model_name="limitecalidad",
            name="c1",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="limitecalidad",
            name="c2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
