# Generated by Django 5.1.6 on 2025-10-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0025_tiposcalidad_remove_limitecalidad_tipo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tiposcalidad",
            old_name="is_C_1",
            new_name="is_c_1",
        ),
        migrations.RenameField(
            model_name="tiposcalidad",
            old_name="is_C_2",
            new_name="is_c_2",
        ),
    ]
