# Generated by Django 5.1.6 on 2025-10-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0026_rename_is_c_1_tiposcalidad_is_c_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elementoanalisis",
            name="es_aditivo",
        ),
        migrations.RemoveField(
            model_name="elementoanalisis",
            name="es_contaminante",
        ),
        migrations.RemoveField(
            model_name="elementoanalisis",
            name="es_desgaste",
        ),
    ]
