# Generated by Django 5.1.6 on 2025-10-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0027_remove_elementoanalisis_es_aditivo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="limiteelemento",
            old_name="limite_amarillo",
            new_name="valor",
        ),
        migrations.RemoveField(
            model_name="limiteelemento",
            name="elemento",
        ),
        migrations.RemoveField(
            model_name="limiteelemento",
            name="limite_rojo",
        ),
        migrations.RemoveField(
            model_name="limiteelemento",
            name="limite_verde",
        ),
        migrations.AddField(
            model_name="limiteelemento",
            name="nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="limiteelemento",
            name="symbol_operation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("<", "Menor que"),
                    ("<=", "Menor o igual"),
                    ("=", "Igual"),
                    (">=", "Mayor o igual"),
                    (">", "Mayor que"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="limiteelemento",
            name="type_operation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
