# Generated by Django 5.1.6 on 2025-10-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0028_rename_limite_amarillo_limiteelemento_valor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LimiteElemento",
        ),
        migrations.AddField(
            model_name="elementoanalisis",
            name="symbol_operation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("<", "Menor que"),
                    ("<=", "Menor o igual"),
                    ("=", "Igual"),
                    (">=", "Mayor o igual"),
                    (">", "Mayor que"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="elementoanalisis",
            name="valor",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
