# Generated by Django 5.1.6 on 2025-10-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0029_delete_limiteelemento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
