# Generated by Django 5.1.6 on 2026-06-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0031_reconcile_sample_technical_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="extrafield",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="extrafield",
            name="usuario_actualizacion",
        ),
        migrations.RemoveField(
            model_name="extrafield",
            name="usuario_creacion",
        ),
        migrations.RemoveField(
            model_name="extrafield",
            name="usuario_ultima_edicion",
        ),
        migrations.RemoveField(
            model_name="submetodoprueba",
            name="metodo",
        ),
        migrations.AlterUniqueTogether(
            name="pruebasubmetodotecnico",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="pruebasubmetodotecnico",
            name="prueba",
        ),
        migrations.RemoveField(
            model_name="pruebasubmetodotecnico",
            name="submetodo",
        ),
        migrations.RemoveField(
            model_name="prueba",
            name="submetodos_tecnicos",
        ),
        migrations.DeleteModel(
            name="Rol",
        ),
        migrations.DeleteModel(
            name="ExtraField",
        ),
        migrations.DeleteModel(
            name="MetodoPrueba",
        ),
        migrations.DeleteModel(
            name="PruebaSubmetodoTecnico",
        ),
        migrations.DeleteModel(
            name="SubmetodoPrueba",
        ),
    ]
