# Generated by Django 5.1.6 on 2026-07-05 21:22

import django.db.models.deletion
from django.db import migrations, models


def normalize_component_types(apps, schema_editor):
    Component = apps.get_model("misc", "PruebaResultadoComponente")
    Component.objects.filter(tipo_dato="texto").update(tipo_dato="comentario")
    Component.objects.filter(tipo_dato="opcion").update(tipo_dato="escala")
    Component.objects.filter(tipo_dato="escala_ordinal").update(tipo_dato="escala")


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0034_pruebafuentelimite_configuracion_regla"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterioevaluacionlimite",
            name="valores_limite",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pruebafuentelimite",
            name="modo_seleccion",
            field=models.CharField(
                choices=[
                    (
                        "desde_muestra_editable",
                        "Tomar de la muestra y permitir reemplazo",
                    ),
                    ("seleccionar_asignacion", "Seleccionar al asignar la prueba"),
                    ("fijo", "Usar configuración fija"),
                ],
                default="seleccionar_asignacion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pruebafuentelimite",
            name="publicada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pruebafuentelimite",
            name="reglas_resultados",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pruebafuentelimite",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="pruebaresultadocomponente",
            name="etiqueta_falso",
            field=models.CharField(blank=True, default="No", max_length=80),
        ),
        migrations.AddField(
            model_name="pruebaresultadocomponente",
            name="etiqueta_verdadero",
            field=models.CharField(blank=True, default="Sí", max_length=80),
        ),
        migrations.AddField(
            model_name="pruebaresultadocomponente",
            name="unidad_catalogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="componentes_resultado",
                to="misc.unidad",
            ),
        ),
        migrations.RunPython(normalize_component_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pruebaresultadocomponente",
            name="tipo_dato",
            field=models.CharField(
                choices=[
                    ("numerico", "Numérico"),
                    ("booleano", "Booleano"),
                    ("escala", "Escala"),
                    ("comentario", "Comentario"),
                ],
                default="numerico",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CriterioCatalogoSeleccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="misc.catalogotecnico",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selecciones_catalogo",
                        to="misc.criterioevaluacionlimite",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="misc.catalogotecnicoitem",
                    ),
                ),
            ],
            options={
                "ordering": ["catalogo__orden", "catalogo__nombre"],
                "unique_together": {("criterio", "catalogo")},
            },
        ),
        migrations.CreateModel(
            name="PruebaFuenteCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "campo_tecnico_muestra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuentes_limite_configuradas",
                        to="misc.campotecnicomuestra",
                    ),
                ),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuentes_limite_configuradas",
                        to="misc.catalogotecnico",
                    ),
                ),
                (
                    "fuente_limite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogos_configurados",
                        to="misc.pruebafuentelimite",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
                "unique_together": {("fuente_limite", "catalogo")},
            },
        ),
    ]
