# Generated by Django 5.1.6 on 2026-07-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0035_criterioevaluacionlimite_valores_limite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pruebalimitecampo",
            name="tipo_comparacion",
            field=models.CharField(
                choices=[
                    ("numerica", "Numerica"),
                    ("booleano", "Booleano"),
                    ("escala", "Escala"),
                    ("informativo", "Informativo"),
                ],
                default="numerica",
                max_length=30,
            ),
        ),
    ]
