# Generated by Django 5.1.6 on 2026-07-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0036_alter_pruebalimitecampo_tipo_comparacion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PruebaLimiteValorItem",
        ),
    ]
