# Generated by Django 5.1.6 on 2026-09-11 13:17

import django.db.models.deletion
from django.db import migrations, models


def create_initial_catalog_versions(apps, schema_editor):
    Catalog = apps.get_model('misc', 'CatalogoTecnico')
    Version = apps.get_model('misc', 'CatalogoTecnicoVersion')
    Item = apps.get_model('misc', 'CatalogoTecnicoItem')
    for catalog in Catalog.objects.all().iterator():
        version, _ = Version.objects.get_or_create(
            catalogo=catalog,
            numero=1,
            defaults={'nombre': 'Versión inicial'},
        )
        Catalog.objects.filter(pk=catalog.pk).update(version_actual=version)
        Item.objects.filter(catalogo=catalog, version__isnull=True).update(version=version)


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0044_remove_yellow_escalation_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoTecnicoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('norma_referencia', models.CharField(blank=True, max_length=160)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='misc.catalogotecnico')),
            ],
            options={
                'ordering': ['catalogo', '-numero'],
                'unique_together': {('catalogo', 'numero')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='catalogotecnicoitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='catalogotecnico',
            name='version_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogos_actuales', to='misc.catalogotecnicoversion'),
        ),
        migrations.AddField(
            model_name='catalogotecnicoitem',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='misc.catalogotecnicoversion'),
        ),
        migrations.RunPython(create_initial_catalog_versions, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='catalogotecnicoitem',
            unique_together={('version', 'codigo')},
        ),
    ]
