# Generated by Django 5.1.6 on 2026-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricoResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultado_anterior", models.FloatField()),
                ("fecha_medicion_anterior", models.DateTimeField()),
                ("observaciones_anterior", models.TextField(blank=True, null=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now_add=True)),
                ("motivo_cambio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultado", models.TextField()),
                ("fecha_medicion", models.DateTimeField()),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("preliminar", "Preliminar"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RevisionResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estatus_anterior",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("estatus_nuevo", models.CharField(max_length=20)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_revision", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
