# Generated by Django 5.1.6 on 2026-04-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("muestras", "0002_initial"),
        ("resultado", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicoresultado",
            name="usuario_medicion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicoresultado",
            name="usuario_modificacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modificaciones_resultados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultado",
            name="prueba_muestra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="muestras.pruebamuestra",
            ),
        ),
        migrations.AddField(
            model_name="resultado",
            name="usuario_medicion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultados_medidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicoresultado",
            name="resultado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico",
                to="resultado.resultado",
            ),
        ),
        migrations.AddField(
            model_name="revisionresultado",
            name="resultado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisiones",
                to="resultado.resultado",
            ),
        ),
        migrations.AddField(
            model_name="revisionresultado",
            name="usuario_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
