# Generated by Django 5.1.6 on 2025-05-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoresultado',
            name='equipo_laboratorio',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='equipo_laboratorio',
        ),
    ]
