# Generated by Django 5.1.6 on 2026-05-27 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0003_muestra_muestras_mu_fecha_t_a0826a_idx_and_more"),
        ("resultado", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="historicoresultado",
            index=models.Index(
                fields=["resultado", "fecha_modificacion"],
                name="resultado_h_resulta_28b3cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resultado",
            index=models.Index(
                fields=["prueba_muestra", "estatus"],
                name="resultado_r_prueba__20050e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resultado",
            index=models.Index(
                fields=["fecha_medicion"], name="resultado_r_fecha_m_83b178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resultado",
            index=models.Index(
                fields=["fecha_registro"], name="resultado_r_fecha_r_3c66c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revisionresultado",
            index=models.Index(
                fields=["resultado", "fecha_revision"],
                name="resultado_r_resulta_5f139f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revisionresultado",
            index=models.Index(
                fields=["estatus_nuevo"], name="resultado_r_estatus_84b94c_idx"
            ),
        ),
    ]
