# Generated by Django 5.1.6 on 2025-10-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resultado", "0003_remove_historicoresultado_equipo_laboratorio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultado",
            name="resultado",
            field=models.TextField(),
        ),
    ]
