# Generated by Django 5.1.6 on 2026-08-09 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0024_optimize_workflow_queries"),
        ("resultado", "0004_alter_historicoresultado_resultado_anterior"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="resultado",
            index=models.Index(
                fields=["prueba_muestra", "fecha_registro"],
                name="resultado_r_prueba__28036a_idx",
            ),
        ),
    ]
