# Generated by Django 5.1.6 on 2025-05-01 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
        ('muestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado')], default='borrador', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInterpretacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_obtenido', models.FloatField()),
                ('nivel', models.CharField(choices=[('verde', 'Verde - Normal'), ('amarillo', 'Amarillo - Precaución'), ('rojo', 'Rojo - Peligro')], max_length=10)),
                ('comentario_automatico', models.TextField(blank=True, null=True)),
                ('comentario_manual', models.TextField(blank=True, null=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misc.elementoanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='Interpretacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_proveedor', models.TextField(blank=True, null=True)),
                ('fecha_interpretacion', models.DateTimeField(auto_now_add=True)),
                ('muestra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interpretacion', to='muestras.muestra')),
            ],
        ),
    ]
