# Generated by Django 5.1.6 on 2025-05-01 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muestras', '0002_initial'),
        ('reporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleinterpretacion',
            name='interpretacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reporte.interpretacion'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='muestra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='muestras.muestra'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario_emision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_emitidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='detalleinterpretacion',
            unique_together={('interpretacion', 'elemento')},
        ),
    ]
