# Generated by Django 5.1.6 on 2026-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporte", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interpretacion",
            name="muestra",
        ),
        migrations.RemoveField(
            model_name="interpretacion",
            name="usuario",
        ),
        migrations.AlterField(
            model_name="reporte",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("pendiente_aprobacion", "Pendiente de aprobacion"),
                    ("aprobado", "Aprobado"),
                    ("enviado", "Enviado"),
                ],
                default="borrador",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="DetalleInterpretacion",
        ),
        migrations.DeleteModel(
            name="Interpretacion",
        ),
    ]
