# Generated by Django 5.1.6 on 2025-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporte", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reporte",
            old_name="observaciones",
            new_name="comentarios",
        ),
        migrations.AddField(
            model_name="reporte",
            name="Responsable",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="conclusiones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="firma_ruta",
            field=models.TextField(blank=True, null=True),
        ),
    ]
