# Generated by Django 5.1.6 on 2025-10-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporte", "0003_rename_observaciones_reporte_comentarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporte",
            name="with_limites",
            field=models.BooleanField(default=True),
        ),
    ]
