# Generated by Django 5.1.6 on 2026-06-04 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0013_pruebamuestra_criterio_limite_catalogo_and_more"),
        ("reporte", "0003_remove_interpretacion_muestra_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "Email"), ("app", "Aplicacion")],
                        max_length=20,
                    ),
                ),
                (
                    "destinatario_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("enviado", "Enviado"), ("fallido", "Fallido")],
                        default="enviado",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.AlterModelOptions(
            name="reporte",
            options={"ordering": ["-fecha_emision", "-id"]},
        ),
        migrations.AddField(
            model_name="reporte",
            name="fecha_envio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="fecha_generacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes",
                to="muestras.lotemuestras",
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="notas_internas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="usuario_envio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_enviados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reporte",
            name="visible_cliente",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="consecutivo",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("pendiente_aprobacion", "Pendiente de aprobacion"),
                    ("generado", "Generado"),
                    ("aprobado", "Aprobado"),
                    ("enviado", "Enviado"),
                    ("anulado", "Anulado"),
                ],
                default="generado",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="muestra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes",
                to="muestras.muestra",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reporte",
            unique_together={("muestra", "version")},
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["lote", "version"], name="reporte_rep_lote_id_fce0ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["estatus"], name="reporte_rep_estatus_712bca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["visible_cliente"], name="reporte_rep_visible_bfd2ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["fecha_emision"], name="reporte_rep_fecha_e_f36725_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["fecha_envio"], name="reporte_rep_fecha_e_61a0d7_idx"
            ),
        ),
        migrations.AddField(
            model_name="reporteenvio",
            name="destinatario_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_recibidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporteenvio",
            name="enviado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envios_reportes_realizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporteenvio",
            name="reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envios",
                to="reporte.reporte",
            ),
        ),
    ]
