# Generated by Django 5.1.6 on 2025-05-01 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField()),
                ('condiciones_entrega', models.TextField(blank=True, null=True)),
                ('campos_adicionales', models.JSONField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_toma', models.DateTimeField()),
                ('contacto_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_placa', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_servicio_aceite', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_periodo_aceite', models.CharField(blank=True, choices=[('horas', 'Horas'), ('km', 'Kilómetros'), ('millas', 'Millas'), ('dias', 'Días')], max_length=10, null=True)),
                ('periodo_servicio_equipo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_periodo_equipo', models.CharField(blank=True, choices=[('horas', 'Horas'), ('km', 'Kilómetros'), ('millas', 'Millas'), ('dias', 'Días')], max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('campos_adicionales', models.JSONField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
