# Generated by Django 5.1.6 on 2026-05-27 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0004_carpeta_activestree_compani_8bb7c0_idx_and_more"),
        ("misc", "0002_initial"),
        ("muestras", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["fecha_toma"], name="muestras_mu_fecha_t_a0826a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["referencia_equipo", "fecha_toma"],
                name="muestras_mu_referen_32e234_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["lubricante"], name="muestras_mu_lubrica_14ffca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["is_ingresado", "is_revisado"],
                name="muestras_mu_is_ingr_208627_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pruebamuestra",
            index=models.Index(
                fields=["muestra", "estatus"], name="muestras_pr_muestra_bcd9cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebamuestra",
            index=models.Index(
                fields=["prueba", "estatus"], name="muestras_pr_prueba__9f18c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebamuestra",
            index=models.Index(
                fields=["fecha_solicitud"], name="muestras_pr_fecha_s_59ce34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebamuestra",
            index=models.Index(
                fields=["fecha_medicion"], name="muestras_pr_fecha_m_5c84f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebamuestra",
            index=models.Index(
                fields=["fecha_revision"], name="muestras_pr_fecha_r_480ca6_idx"
            ),
        ),
    ]
