# Generated by Django 5.1.6 on 2025-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='is_ingresado',
            field=models.BooleanField(default=False),
        ),
    ]
