# Generated by Django 5.1.6 on 2025-05-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0003_muestra_is_ingresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='is_aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muestra',
            name='was_checked',
            field=models.DateField(default='2025-05-01'),
        ),
    ]
