# Generated by Django 5.1.6 on 2026-05-27 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0004_carpeta_activestree_compani_8bb7c0_idx_and_more"),
        ("misc", "0002_initial"),
        ("muestras", "0003_muestra_muestras_mu_fecha_t_a0826a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="muestra",
            name="aditivo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="muestra",
            name="condicion",
            field=models.CharField(
                choices=[("nueva", "Nueva"), ("usada", "Usada")],
                default="usada",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="muestra",
            name="espesante",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="muestra",
            name="fecha_envio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muestra",
            name="nivel_desempeno",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="muestra",
            name="nlgi",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="muestra",
            name="tipo_muestra",
            field=models.CharField(
                choices=[("aceite", "Aceite"), ("grasa", "Grasa")],
                default="aceite",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="muestra",
            name="uso",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name="LoteMuestras",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("registrado", "Cliente registrado"),
                            ("ocasional", "Cliente ocasional"),
                        ],
                        default="registrado",
                        max_length=20,
                    ),
                ),
                (
                    "cliente_ocasional_nombre",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "contacto_nombre",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "contacto_telefono",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contacto_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("fecha_envio", models.DateField()),
                ("fecha_recepcion", models.DateField(blank=True, null=True)),
                (
                    "tipo_gestion",
                    models.CharField(
                        choices=[
                            ("comercial", "comercial"),
                            ("postventa", "postventa"),
                            ("pqrs", "PQRS"),
                        ],
                        default="rutinaria",
                        max_length=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("registrado", "Registrado"),
                            ("recibido", "Recibido"),
                            ("en_laboratorio", "En laboratorio"),
                            ("en_analisis", "En análisis"),
                            ("parcial", "Parcial"),
                            ("resultados_completos", "Resultados completos"),
                            ("revisado", "Revisado"),
                            ("reportado", "Reportado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="registrado",
                        max_length=30,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente_empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_muestras",
                        to="misc.empresa",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_muestras_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.AddField(
            model_name="muestra",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="muestras",
                to="muestras.lotemuestras",
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(fields=["lote"], name="muestras_mu_lote_id_36c628_idx"),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["fecha_envio"], name="muestras_mu_fecha_e_10c6d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["tipo_muestra"], name="muestras_mu_tipo_mu_748b1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["condicion"], name="muestras_mu_condici_caa9d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lotemuestras",
            index=models.Index(
                fields=["tipo_cliente"], name="muestras_lo_tipo_cl_850b65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lotemuestras",
            index=models.Index(fields=["estado"], name="muestras_lo_estado_0952eb_idx"),
        ),
        migrations.AddIndex(
            model_name="lotemuestras",
            index=models.Index(
                fields=["fecha_envio"], name="muestras_lo_fecha_e_f7de70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lotemuestras",
            index=models.Index(
                fields=["tipo_gestion"], name="muestras_lo_tipo_ge_0cbaf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lotemuestras",
            index=models.Index(
                fields=["cliente_empresa", "fecha_envio"],
                name="muestras_lo_cliente_092b6c_idx",
            ),
        ),
    ]
