# Generated by Django 5.1.6 on 2025-05-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0004_muestra_is_aprobado_muestra_was_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebamuestra',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
