# Generated by Django 5.1.6 on 2026-05-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0008_tipogestionmuestra"),
        (
            "muestras",
            "0004_muestra_aditivo_muestra_condicion_muestra_espesante_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lotemuestras",
            new_name="muestras_lo_tipo_ge_eca143_idx",
            old_name="muestras_lo_tipo_ge_0cbaf9_idx",
        ),
        migrations.AlterField(
            model_name="lotemuestras",
            name="tipo_gestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes_muestras",
                to="misc.tipogestionmuestra",
            ),
        ),
    ]
