# Generated by Django 5.1.6 on 2025-05-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activesTree', '0001_initial'),
        ('muestras', '0005_pruebamuestra_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='Equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='activesTree.maquina'),
        ),
    ]
