# Generated by Django 5.1.6 on 2026-05-29 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0004_carpeta_activestree_compani_8bb7c0_idx_and_more"),
        ("misc", "0010_aditivograsa_espesantegrasa_fabricantelubricante_and_more"),
        (
            "muestras",
            "0005_rename_muestras_lo_tipo_ge_0cbaf9_idx_muestras_lo_tipo_ge_eca143_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_fecha_t_a0826a_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_referen_32e234_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_lubrica_14ffca_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_is_ingr_208627_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_lote_id_36c628_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_fecha_e_10c6d6_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_tipo_mu_748b1d_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_condici_caa9d5_idx",
        ),
        migrations.AddField(
            model_name="muestra",
            name="aditivo_desconocido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="muestra",
            name="espesante_desconocido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="muestra",
            name="fabricante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muestras",
                to="misc.fabricantelubricante",
            ),
        ),
        migrations.AddField(
            model_name="muestra",
            name="fabricante_otro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="muestra",
            name="fabricante_otro_nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="muestra",
            name="grado_viscosidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muestras",
                to="misc.gradoviscosidad",
            ),
        ),
        migrations.AddField(
            model_name="muestra",
            name="grado_viscosidad_desconocido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="muestra",
            name="limites_aplicables",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="muestra",
            name="nivel_desempeno_desconocido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="muestra",
            name="nlgi_desconocido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="muestra",
            name="referencia_marca",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="muestra",
            name="uso_desconocido",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="muestra",
            name="aditivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muestras",
                to="misc.aditivograsa",
            ),
        ),
        migrations.AlterField(
            model_name="muestra",
            name="espesante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muestras",
                to="misc.espesantegrasa",
            ),
        ),
        migrations.AlterField(
            model_name="muestra",
            name="lubricante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muestras_historicas",
                to="misc.lubricante",
            ),
        ),
        migrations.AlterField(
            model_name="muestra",
            name="nivel_desempeno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muestras",
                to="misc.niveldesempeno",
            ),
        ),
        migrations.AlterField(
            model_name="muestra",
            name="nlgi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muestras",
                to="misc.nlgi",
            ),
        ),
        migrations.AlterField(
            model_name="muestra",
            name="uso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muestras",
                to="misc.usolubricante",
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["fabricante"], name="muestras_mu_fabrica_394b9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["grado_viscosidad"], name="muestras_mu_grado_v_b51f89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["nivel_desempeno"], name="muestras_mu_nivel_d_9813f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(fields=["uso"], name="muestras_mu_uso_id_163e13_idx"),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(fields=["nlgi"], name="muestras_mu_nlgi_id_105716_idx"),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["aditivo"], name="muestras_mu_aditivo_ed4181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["espesante"], name="muestras_mu_espesan_25a63d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["limites_aplicables"], name="muestras_mu_limites_fe9d27_idx"
            ),
        ),
    ]
