# Generated by Django 5.1.6 on 2026-05-29 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0006_remove_muestra_muestras_mu_fecha_t_a0826a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleBatchExcelTemplateToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "schema_version",
                    models.CharField(default="sample-batch-v1", max_length=50),
                ),
                ("filename", models.CharField(blank=True, max_length=180, null=True)),
                (
                    "cliente_empresa_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sample_batch_excel_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="muestras_sa_token_01563a_idx"),
                    models.Index(
                        fields=["schema_version"], name="muestras_sa_schema__8749d2_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="muestras_sa_expires_f79e18_idx"
                    ),
                ],
            },
        ),
    ]
