# Generated by Django 5.1.6 on 2025-09-29 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activesTree",
            "0006_alter_maquina_codigo_equipo_alter_maquina_componente_and_more",
        ),
        ("muestras", "0006_muestra_equipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="muestra",
            name="Equipo",
        ),
        migrations.AlterField(
            model_name="muestra",
            name="referencia_equipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="activesTree.maquina",
            ),
        ),
    ]
