# Generated by Django 5.1.6 on 2025-10-08 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0007_remove_muestra_equipo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pruebamuestra",
            options={
                "verbose_name": "Prueba aplicada a muestra",
                "verbose_name_plural": "Pruebas aplicadas a muestras",
            },
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_proceso", "En Proceso"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                    ("aprobado", "Aprobado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="fecha_medicion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="fecha_revision",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="unidad",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="usuario_medicion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pruebas_medidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="usuario_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pruebas_revisadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="valor",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pruebamuestra",
            name="usuario_solicitud",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pruebas_solicitadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
