# Generated by Django 5.1.6 on 2026-05-29 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0007_samplebatchexceltemplatetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngresoLabLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_recepcion", models.DateTimeField()),
                ("condiciones_entrega", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("campos_adicionales", models.JSONField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "lote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingreso_lab_lote",
                        to="muestras.lotemuestras",
                    ),
                ),
                (
                    "usuario_recepcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_recepcion"],
                "indexes": [
                    models.Index(
                        fields=["lote"], name="muestras_in_lote_id_dafc7c_idx"
                    ),
                    models.Index(
                        fields=["fecha_recepcion"],
                        name="muestras_in_fecha_r_dd6d53_idx",
                    ),
                    models.Index(
                        fields=["usuario_recepcion"],
                        name="muestras_in_usuario_a72bb7_idx",
                    ),
                ],
            },
        ),
    ]
