# Generated by Django 5.1.6 on 2025-10-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0008_alter_pruebamuestra_options_pruebamuestra_estatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="muestra",
            name="is_resultado_ingresado",
            field=models.BooleanField(default=False),
        ),
    ]
