# Generated by Django 5.1.6 on 2026-05-30 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0011_catalogotecnico_catalogotecnicocampo_and_more"),
        ("muestras", "0008_ingresolablote"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuestraAtributoTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desconocido", models.BooleanField(default=False)),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atributos_muestra",
                        to="misc.catalogotecnico",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atributos_muestra",
                        to="misc.catalogotecnicoitem",
                    ),
                ),
                (
                    "muestra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atributos_tecnicos",
                        to="muestras.muestra",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["muestra", "catalogo"],
                        name="muestras_mu_muestra_90104b_idx",
                    ),
                    models.Index(
                        fields=["catalogo", "item"],
                        name="muestras_mu_catalog_294688_idx",
                    ),
                    models.Index(
                        fields=["desconocido"], name="muestras_mu_descono_44c655_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("muestra", "catalogo"),
                        name="unique_sample_dynamic_catalog_attribute",
                    )
                ],
            },
        ),
    ]
