# Generated by Django 5.1.6 on 2025-10-08 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0009_muestra_is_resultado_ingresado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pruebamuestra",
            name="muestra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="muestras.muestra",
            ),
        ),
    ]
