# Generated by Django 5.1.6 on 2026-05-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0009_muestraatributotecnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="pruebamuestra",
            name="estado_limite",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="evaluacion_limite",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
