# Generated by Django 5.1.6 on 2025-10-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0010_alter_pruebamuestra_muestra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pruebamuestra",
            name="valor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
