# Generated by Django 5.1.6 on 2026-05-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0010_pruebamuestra_estado_limite_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_fabrica_394b9c_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_grado_v_b51f89_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_nivel_d_9813f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_uso_id_163e13_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_nlgi_id_105716_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_aditivo_ed4181_idx",
        ),
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_espesan_25a63d_idx",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="aditivo",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="aditivo_desconocido",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="espesante",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="espesante_desconocido",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="fabricante",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="fabricante_otro",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="fabricante_otro_nombre",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="grado_viscosidad",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="grado_viscosidad_desconocido",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="lubricante",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="nivel_desempeno",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="nivel_desempeno_desconocido",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="nlgi",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="nlgi_desconocido",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="uso",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="uso_desconocido",
        ),
    ]
