# Generated by Django 5.1.6 on 2025-10-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0011_alter_pruebamuestra_valor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="muestra",
            old_name="is_aprobado",
            new_name="is_revisado",
        ),
    ]
