# Generated by Django 5.1.6 on 2026-06-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "misc",
            "0022_lotepruebaspredefinidodetalle_criterio_limite_catalogo_and_more",
        ),
        ("muestras", "0012_pruebamuestra_asignacion_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="pruebamuestra",
            name="criterio_limite_catalogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pruebas_muestra_criterio",
                to="misc.catalogotecnico",
            ),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="criterio_limite_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pruebas_muestra_criterio",
                to="misc.catalogotecnicoitem",
            ),
        ),
    ]
