# Generated by Django 5.1.6 on 2025-10-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0012_rename_is_aprobado_muestra_is_revisado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pruebamuestra",
            old_name="is_used",
            new_name="is_revisada",
        ),
    ]
