# Generated by Django 5.1.6 on 2026-06-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0025_alter_pruebafuentelimite_unique_together_and_more"),
        ("muestras", "0013_pruebamuestra_criterio_limite_catalogo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pruebamuestra",
            name="criterio_limite_escala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pruebas_muestra_criterio",
                to="misc.escalacomparacion",
            ),
        ),
        migrations.AddField(
            model_name="pruebamuestra",
            name="criterio_limite_escala_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pruebas_muestra_criterio",
                to="misc.escalacomparacionitem",
            ),
        ),
    ]
