# Generated by Django 5.1.6 on 2026-06-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0016_sample_field_and_evaluation_criterion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="muestraatributotecnico",
            new_name="muestras_mu_muestra_8645c2_idx",
            old_name="muestras_mu_muestra_1ec2f8_idx",
        ),
    ]
