# Generated by Django 5.1.6 on 2026-07-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0020_delete_ingresolab"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="muestra",
            name="muestras_mu_limites_fe9d27_idx",
        ),
        migrations.RemoveField(
            model_name="muestra",
            name="limites_aplicables",
        ),
    ]
