# Generated by Django 5.1.6 on 2026-07-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muestras", "0022_pruebamuestra_result_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialMuestra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(default="actualizacion", max_length=30)),
                ("cambios", models.JSONField(default=dict)),
                ("estado_anterior", models.JSONField(default=dict)),
                ("estado_nuevo", models.JSONField(default=dict)),
                ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "muestra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="muestras.muestra",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cambios_muestras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en", "-id"],
                "indexes": [
                    models.Index(
                        fields=["muestra", "creado_en"],
                        name="muestras_hi_muestra_753dc9_idx",
                    )
                ],
            },
        ),
    ]
