# Generated by Django 5.1.6 on 2026-08-09 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0007_sampling_points"),
        ("misc", "0044_remove_yellow_escalation_thresholds"),
        ("muestras", "0023_historialmuestra"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["lote", "is_ingresado"], name="muestras_mu_lote_id_1062c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["lote", "is_resultado_ingresado"],
                name="muestras_mu_lote_id_33b95f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["lote", "is_revisado"], name="muestras_mu_lote_id_535ca9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["referencia_equipo", "fecha_toma"],
                name="muestras_mu_referen_32e234_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="muestra",
            index=models.Index(
                fields=["fecha_registro"], name="muestras_mu_fecha_r_2f1a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebamuestra",
            index=models.Index(
                fields=["muestra", "estado_asignacion"],
                name="muestras_pr_muestra_c888ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pruebamuestra",
            index=models.Index(
                fields=["muestra", "completada"], name="muestras_pr_muestra_b346f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pruebamuestra",
            index=models.Index(
                fields=["muestra", "is_revisada"], name="muestras_pr_muestra_614986_idx"
            ),
        ),
    ]
