# Generated by Django 5.1.6 on 2026-09-05 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0024_optimize_workflow_queries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemuestras',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotemuestras',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotemuestras',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='muestra',
            name='estado_operativo',
            field=models.CharField(choices=[('activa', 'Activa'), ('invalidada', 'Invalidada')], db_index=True, default='activa', max_length=20),
        ),
        migrations.AddField(
            model_name='muestra',
            name='fecha_invalidacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='invalidada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_invalidadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muestra',
            name='motivo_invalidacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
