from .muestras.index import MuestraSerializer,CreateMuestraSerializer
from .pruebasMuestra.index import PruebaMuestraSerializer, CreatePruebaMuestraSerializer
from .ingresoLab.index import IngresoLabSerializer