# Generated by Django 5.1.6 on 2026-06-05 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0023_empresa_block_reason_empresa_blocked_at_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_status",
            field=models.CharField(
                choices=[
                    ("PENDING_INVITATION", "Pendiente invitacion"),
                    ("ACTIVE", "Activo"),
                    ("BLOCKED", "Bloqueado"),
                    ("READ_ONLY", "Solo lectura"),
                    ("DISABLED", "Deshabilitado"),
                ],
                db_index=True,
                default="PENDING_INVITATION",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="block_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_read_only",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SecurityPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=80)),
                ("action", models.CharField(max_length=80)),
                ("code", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["module", "action"],
                "indexes": [
                    models.Index(
                        fields=["module", "active"],
                        name="users_secur_module_f3118c_idx",
                    )
                ],
                "unique_together": {("module", "action")},
            },
        ),
        migrations.CreateModel(
            name="SecurityRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=80, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "GlobalOil"),
                            ("COMPANY", "Empresa"),
                            ("INTERNAL", "Interno"),
                        ],
                        default="COMPANY",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("editable", models.BooleanField(default=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "legacy_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GLOBAL", "GlobalOil"),
                            ("ADMINISTRADOR", "Administrador"),
                            ("EMPRESA", "Empresa"),
                            ("LABORATORISTA", "Laboratorista"),
                            ("OPERARIO", "Operario"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scope", "name"],
                "indexes": [
                    models.Index(
                        fields=["scope", "active"], name="users_secur_scope_0adab2_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allowed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_roles",
                        to="users.securitypermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="users.securityrole",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["role", "allowed"],
                        name="users_secur_role_id_6c623b_idx",
                    ),
                    models.Index(
                        fields=["permission", "allowed"],
                        name="users_secur_permiss_91f3a4_idx",
                    ),
                ],
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=120)),
                (
                    "module",
                    models.CharField(db_index=True, default="users", max_length=80),
                ),
                ("detail", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_audit_events",
                        to="misc.empresa",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "created_at"],
                        name="users_usera_empresa_1de731_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="users_usera_actor_i_dacf5d_idx",
                    ),
                    models.Index(
                        fields=["target_user", "created_at"],
                        name="users_usera_target__6c530c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserCompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_company_admin", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ACTIVE", "Activo"),
                            ("BLOCKED", "Bloqueado"),
                            ("READ_ONLY", "Solo lectura"),
                            ("REMOVED", "Removido"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("block_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="misc.empresa",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profiles",
                        to="users.securityrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["empresa", "status"],
                        name="users_userc_empresa_c09bc2_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="users_userc_user_id_70c9e5_idx"
                    ),
                ],
                "unique_together": {("user", "empresa")},
            },
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ACCEPTED", "Aceptada"),
                            ("EXPIRED", "Expirada"),
                            ("REVOKED", "Revocada"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_company_admin", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_invitations",
                        to="misc.empresa",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_invitations",
                        to="users.securityrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "status"],
                        name="users_useri_empresa_d08840_idx",
                    ),
                    models.Index(
                        fields=["email", "status"], name="users_useri_email_79a4bf_idx"
                    ),
                ],
            },
        ),
    ]
