# Generated by ChatGPT on 2026-06-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_seed_security_defaults"),
        ("misc", "0023_empresa_block_reason_empresa_blocked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="misc.empresa",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="block_scope",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin bloqueo"),
                    ("GLOBAL", "Bloqueo GlobalOil"),
                    ("COMPANY", "Bloqueo empresa"),
                ],
                db_index=True,
                default="NONE",
                max_length=20,
            ),
        ),
    ]
