# Generated by Django 5.1.6 on 2026-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalisisLubricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("propietario", models.CharField(max_length=255)),
                ("fecha_muestreo", models.DateField()),
                ("nombre_equipo", models.CharField(max_length=255)),
                ("modelo", models.CharField(max_length=255)),
                ("horas_km_aceite", models.IntegerField()),
                ("id_placa", models.CharField(max_length=255)),
                ("lugar_trabajo", models.CharField(max_length=255)),
                ("horas_km_equipo", models.IntegerField()),
                ("ref_aceite", models.CharField(max_length=255)),
                ("no_interno_lab", models.CharField(max_length=255, unique=True)),
                ("fecha_recepcion", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Carpeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_pt_medida", models.BooleanField(default=False)),
                ("id_parent_node", models.CharField(default="-1", max_length=255)),
                ("nombre", models.CharField(max_length=255)),
                ("parentId", models.CharField(default="root", max_length=255)),
                ("typeFolder", models.CharField(max_length=255)),
                ("isMachine", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("componente", models.CharField(blank=True, max_length=255, null=True)),
                ("tipoAceite", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "frecuenciaCambio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuenciaAnalisis",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "numero_serie",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "codigo_equipo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoMuestrasAceite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observaciones", models.TextField()),
                (
                    "indicadores",
                    models.CharField(default="NO REGISTRA", max_length=255),
                ),
            ],
        ),
    ]
