# Generated by Django 5.1.6 on 2025-05-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activesTree', '0001_initial'),
        ('muestras', '0006_muestra_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='muestras',
            field=models.ForeignKey(default='M20250001', on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='muestras.muestra'),
        ),
    ]
