# Generated by Django 5.1.6 on 2025-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activesTree", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpeta",
            name="parentId",
            field=models.CharField(default="root", max_length=255),
        ),
    ]
