# Generated by Django 5.1.6 on 2026-04-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activesTree", "0001_initial"),
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpeta",
            name="compania",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compañia",
                to="misc.empresa",
            ),
        ),
    ]
