# Generated by Django 5.1.6 on 2025-09-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0002_carpeta_muestras"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carpeta",
            name="muestras",
        ),
    ]
