# Generated by Django 5.1.6 on 2026-04-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activesTree", "0002_initial"),
        ("misc", "0001_initial"),
        ("muestras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpeta",
            name="muestra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="muestra_folder",
                to="muestras.muestra",
            ),
        ),
        migrations.AddField(
            model_name="maquina",
            name="empresa",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="misc.empresa",
            ),
        ),
        migrations.AddField(
            model_name="carpeta",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maquina_folder",
                to="activesTree.maquina",
            ),
        ),
        migrations.AddField(
            model_name="analisislubricante",
            name="Maquina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maquina",
                to="activesTree.maquina",
            ),
        ),
        migrations.AddField(
            model_name="resultadomuestrasaceite",
            name="analisis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="activesTree.analisislubricante",
            ),
        ),
    ]
