# Generated by Django 5.1.6 on 2025-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activesTree", "0002_carpeta_parentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpeta",
            name="isMachine",
            field=models.BooleanField(default=False),
        ),
    ]
