# Generated by Django 5.1.6 on 2025-03-07 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activesTree", "0003_carpeta_ismachine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carpeta",
            old_name="compañia",
            new_name="compania",
        ),
    ]
