# Generated by Django 5.1.6 on 2025-09-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0003_remove_carpeta_muestras"),
        ("misc", "0012_alter_empresa_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="maquina",
            name="empresa",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="misc.empresa",
            ),
        ),
    ]
