# Generated by Django 5.1.6 on 2026-05-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0003_initial"),
        ("misc", "0002_initial"),
        ("muestras", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="carpeta",
            index=models.Index(
                fields=["compania", "typeFolder"], name="activesTree_compani_8bb7c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carpeta",
            index=models.Index(
                fields=["parentId"], name="activesTree_parentI_04b3ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carpeta",
            index=models.Index(
                fields=["id_parent_node"], name="activesTree_id_pare_be7c8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carpeta",
            index=models.Index(
                fields=["machine"], name="activesTree_machine_647737_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carpeta",
            index=models.Index(
                fields=["muestra"], name="activesTree_muestra_1b8267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maquina",
            index=models.Index(
                fields=["empresa", "nombre"], name="activesTree_empresa_677033_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maquina",
            index=models.Index(
                fields=["codigo_equipo"], name="activesTree_codigo__25806e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maquina",
            index=models.Index(
                fields=["numero_serie"], name="activesTree_numero__2684ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maquina",
            index=models.Index(
                fields=["tipoAceite"], name="activesTree_tipoAce_6ae5b8_idx"
            ),
        ),
    ]
