# Generated by Django 5.1.6 on 2025-09-29 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0004_maquina_empresa"),
        ("misc", "0012_alter_empresa_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpeta",
            name="compania",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compañia",
                to="misc.empresa",
            ),
        ),
    ]
