# Generated by Django 5.1.6 on 2025-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activesTree", "0004_rename_compañia_carpeta_compania"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpeta",
            name="id_parent_node",
            field=models.CharField(default="-1", max_length=255),
        ),
    ]
