# Generated by Django 5.1.6 on 2026-05-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0004_carpeta_activestree_compani_8bb7c0_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultadomuestrasaceite",
            name="analisis",
        ),
        migrations.DeleteModel(
            name="AnalisisLubricante",
        ),
        migrations.DeleteModel(
            name="ResultadoMuestrasAceite",
        ),
    ]
