# Generated by Django 5.1.6 on 2026-05-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0005_remove_resultadomuestrasaceite_analisis_and_more"),
        ("misc", "0014_delete_limitecalidad_delete_limitegenericoprueba_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="carpeta",
            name="activesTree_parentI_04b3ec_idx",
        ),
        migrations.RemoveField(
            model_name="carpeta",
            name="parentId",
        ),
        migrations.AlterField(
            model_name="carpeta",
            name="compania",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carpetas",
                to="misc.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="maquina",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="misc.empresa"
            ),
        ),
    ]
