# Generated by Django 5.1.6 on 2025-09-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0005_alter_carpeta_compania"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquina",
            name="codigo_equipo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="maquina",
            name="componente",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="maquina",
            name="frecuenciaAnalisis",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="maquina",
            name="frecuenciaCambio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
