# Generated by Django 5.1.6 on 2025-03-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activesTree", "0005_carpeta_id_parent_node"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maquina",
            name="carpeta",
        ),
        migrations.AddField(
            model_name="carpeta",
            name="is_pt_medida",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="carpeta",
            name="pt_medida",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analisisptmedida",
                to="activesTree.analisislubricante",
            ),
        ),
    ]
