# Generated by Django 5.1.6 on 2025-03-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activesTree", "0006_remove_maquina_carpeta_carpeta_is_pt_medida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpeta",
            name="pt_medida",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analisisptmedida",
                to="activesTree.analisislubricante",
            ),
        ),
        migrations.AlterField(
            model_name="resultadomuestrasaceite",
            name="indicadores",
            field=models.CharField(default="NO REGISTRA", max_length=255),
        ),
    ]
