# Generated by Django 5.1.6 on 2025-09-30 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activesTree",
            "0006_alter_maquina_codigo_equipo_alter_maquina_componente_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="carpeta",
            name="machine",
            field=models.ForeignKey(
                default="11",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maquina_folder",
                to="activesTree.maquina",
            ),
        ),
    ]
