# Generated by Django 5.1.6 on 2025-03-10 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activesTree", "0007_alter_carpeta_pt_medida_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carpeta",
            name="pt_medida",
        ),
    ]
