# Generated by Django 5.1.6 on 2026-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activesTree', '0007_sampling_points'),
        ('misc', '0044_remove_yellow_escalation_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['empresa', 'activo'], name='activesTree_empresa_2ff5b9_idx'),
        ),
    ]
