# Generated by Django 5.1.6 on 2025-09-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0007_carpeta_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpeta",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maquina_folder",
                to="activesTree.maquina",
            ),
        ),
    ]
