# Generated by Django 5.1.6 on 2026-09-18

from django.db import migrations, models


def ensure_machine_tree_nodes(apps, schema_editor):
    Maquina = apps.get_model('activesTree', 'Maquina')
    Carpeta = apps.get_model('activesTree', 'Carpeta')

    for machine in Maquina.objects.filter(activo=True).iterator():
        if Carpeta.objects.filter(machine_id=machine.id).exists():
            continue
        root = Carpeta.objects.filter(
            compania_id=machine.empresa_id,
            typeFolder='root',
        ).order_by('id').first()
        if root is None:
            root = Carpeta.objects.create(
                nombre=getattr(machine.empresa, 'nombre', f'Empresa {machine.empresa_id}'),
                compania_id=machine.empresa_id,
                typeFolder='root',
                id_parent_node='-1',
                isMachine=False,
            )
        Carpeta.objects.create(
            nombre=machine.nombre,
            compania_id=machine.empresa_id,
            typeFolder='machine',
            id_parent_node=str(root.id),
            isMachine=True,
            machine_id=machine.id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('activesTree', '0008_maquina_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(ensure_machine_tree_nodes, migrations.RunPython.noop),
    ]
