# Generated by Django 5.1.6 on 2025-09-30 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activesTree", "0008_alter_carpeta_machine"),
        ("muestras", "0007_remove_muestra_equipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpeta",
            name="muestra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="muestra_folder",
                to="muestras.muestra",
            ),
        ),
    ]
